### ISSUE TITLE
episodes and talks are 500

### ISSUE THREAD

**Issue by eggplants** [melissawahnish/ruby-thursday#5]
I would appreciate it if you could fix some pages in deployment.

<https://rubythursday.com/> => 200

<https://rubythursday.com/episodes> => 500

<https://rubythursday.com/talks> => 500

<img width="742" alt="スクリーンショット 2023-05-01 12 57 50" src="https://user-images.githubusercontent.com/42153744/235404696-efcd915a-fcde-4058-acb7-5dc2619776d3.png">

**Comment by melissawahnish** [comment]
Thanks so much!  I've rebooted the server and the site is back up and
running.

Have a great day!
Melissa
